### ISSUE TITLE
Can't sign up dashboard.hamoni.tech

### ISSUE THREAD

**Issue by QGB** [Hamoni/Realtime-Dashboard-HamoniSync#1]
https://dashboard.hamoni.tech

{"__type":"ResourceNotFoundException","message":"User pool  does not exist."}

**Comment by pmbanugo** [comment]
Hi,

Yes, it's down. I'm working on getting it up. It should be up in a couple of hours

**Comment by pmbanugo** [comment]
This should be working now. I'm marking this as closed. If you've got further enquiries feel free to reach out on pmbanugo@hamoni.chat.
