### ISSUE TITLE
Error while connecting 

### ISSUE THREAD

**Issue by mayuri2307** [Hamoni/Realtime-Dashboard-HamoniSync#2]
![image](https://user-images.githubusercontent.com/31414105/98507317-5b22ce80-2283-11eb-9b47-69bec14f6d2d.png)
Hi,
I am having this error when I run npm start. What is this error and how can I resolve it? I have been trying for 3 days but unable to resolve it.
Thanks!

**Comment by pmbanugo** [comment]
I replied on the other repo https://github.com/pmbanugo/realtime-chartjs-hamoni/issues/1#issuecomment-724247823
